// LUDUS Platform - MongoDB Development Initialization Script
// Generated by Claude (Aether-Render Project Manager) - 2025-01-27 18:45 GMT+3

// Switch to the ludus_dev database
db = db.getSiblingDB('ludus_dev');

// Create collections with validation
db.createCollection('users', {
  validator: {
    $jsonSchema: {
      bsonType: 'object',
      required: ['email', 'name', 'role'],
      properties: {
        email: {
          bsonType: 'string',
          pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        },
        name: {
          bsonType: 'string',
          minLength: 2,
          maxLength: 100
        },
        role: {
          bsonType: 'string',
          enum: ['user', 'partner', 'admin']
        }
      }
    }
  }
});

db.createCollection('activities', {
  validator: {
    $jsonSchema: {
      bsonType: 'object',
      required: ['title', 'description', 'partnerId', 'price'],
      properties: {
        title: {
          bsonType: 'string',
          minLength: 3,
          maxLength: 200
        },
        price: {
          bsonType: 'number',
          minimum: 0
        }
      }
    }
  }
});

db.createCollection('bookings', {
  validator: {
    $jsonSchema: {
      bsonType: 'object',
      required: ['userId', 'activityId', 'status'],
      properties: {
        status: {
          bsonType: 'string',
          enum: ['pending', 'confirmed', 'cancelled', 'completed']
        }
      }
    }
  }
});

// Create indexes for better performance
db.users.createIndex({ email: 1 }, { unique: true });
db.users.createIndex({ phone: 1 }, { unique: true, sparse: true });
db.users.createIndex({ role: 1 });

db.activities.createIndex({ partnerId: 1 });
db.activities.createIndex({ category: 1 });
db.activities.createIndex({ location: '2dsphere' });
db.activities.createIndex({ createdAt: -1 });

db.bookings.createIndex({ userId: 1 });
db.bookings.createIndex({ activityId: 1 });
db.bookings.createIndex({ status: 1 });
db.bookings.createIndex({ createdAt: -1 });

// Create additional collections
db.createCollection('reviews');
db.createCollection('notifications');
db.createCollection('payments');
db.createCollection('categories');
db.createCollection('partners');

// Create indexes for additional collections
db.reviews.createIndex({ activityId: 1 });
db.reviews.createIndex({ userId: 1 });
db.reviews.createIndex({ rating: 1 });

db.notifications.createIndex({ userId: 1 });
db.notifications.createIndex({ createdAt: -1 });

db.payments.createIndex({ userId: 1 });
db.payments.createIndex({ bookingId: 1 });
db.payments.createIndex({ status: 1 });

db.categories.createIndex({ name: 1 }, { unique: true });

db.partners.createIndex({ email: 1 }, { unique: true });
db.partners.createIndex({ status: 1 });

// Insert sample data
db.categories.insertMany([
  { name: 'Sports', nameAr: 'الرياضة', icon: 'sports', description: 'Physical activities and sports' },
  { name: 'Entertainment', nameAr: 'الترفيه', icon: 'entertainment', description: 'Fun and entertainment activities' },
  { name: 'Education', nameAr: 'التعليم', icon: 'education', description: 'Learning and educational activities' },
  { name: 'Food & Dining', nameAr: 'الطعام والمطاعم', icon: 'food', description: 'Culinary experiences and dining' },
  { name: 'Adventure', nameAr: 'المغامرة', icon: 'adventure', description: 'Adventure and outdoor activities' },
  { name: 'Wellness', nameAr: 'العافية', icon: 'wellness', description: 'Health and wellness activities' }
]);

// Create admin user
db.users.insertOne({
  email: 'admin@ludus.sa',
  name: 'LUDUS Admin',
  role: 'admin',
  isActive: true,
  createdAt: new Date(),
  updatedAt: new Date()
});

print('✅ LUDUS development database initialized successfully!');
print('📊 Collections created: users, activities, bookings, reviews, notifications, payments, categories, partners');
print('🔍 Indexes created for optimal performance');
print('👤 Admin user created: admin@ludus.sa');
print('📂 Sample categories inserted');
