#!/bin/bash

# LUDUS Platform - Development Environment Setup Script
# Generated by Claude (Aether-Render Project Manager) - 2025-01-27 18:30 GMT+3

set -e  # Exit on any error

echo "🚀 LUDUS Platform - Development Environment Setup"
echo "=================================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running on macOS
if [[ "$OSTYPE" == "darwin"* ]]; then
    PLATFORM="macOS"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    PLATFORM="Linux"
else
    print_error "Unsupported platform: $OSTYPE"
    exit 1
fi

print_status "Platform detected: $PLATFORM"

# =============================================================================
# 1. CHECK PREREQUISITES
# =============================================================================
print_status "Checking prerequisites..."

# Check Node.js
if command -v node &> /dev/null; then
    NODE_VERSION=$(node --version)
    print_success "Node.js found: $NODE_VERSION"
    
    # Check if version is >= 18
    NODE_MAJOR=$(echo $NODE_VERSION | cut -d'.' -f1 | sed 's/v//')
    if [ "$NODE_MAJOR" -lt 18 ]; then
        print_error "Node.js version 18 or higher is required. Current: $NODE_VERSION"
        exit 1
    fi
else
    print_error "Node.js not found. Please install Node.js 18 or higher."
    print_status "Visit: https://nodejs.org/"
    exit 1
fi

# Check npm
if command -v npm &> /dev/null; then
    NPM_VERSION=$(npm --version)
    print_success "npm found: $NPM_VERSION"
else
    print_error "npm not found. Please install npm."
    exit 1
fi

# Check Python (for AI services)
if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version)
    print_success "Python found: $PYTHON_VERSION"
else
    print_warning "Python3 not found. AI services will not be available."
fi

# Check Docker
if command -v docker &> /dev/null; then
    DOCKER_VERSION=$(docker --version)
    print_success "Docker found: $DOCKER_VERSION"
else
    print_warning "Docker not found. Containerized development will not be available."
fi

# Check MongoDB
if command -v mongod &> /dev/null; then
    MONGODB_VERSION=$(mongod --version | head -n1)
    print_success "MongoDB found: $MONGODB_VERSION"
else
    print_warning "MongoDB not found. Please install MongoDB for local development."
    if [[ "$PLATFORM" == "macOS" ]]; then
        print_status "Install with: brew install mongodb-community"
    elif [[ "$PLATFORM" == "Linux" ]]; then
        print_status "Install with: sudo apt-get install mongodb"
    fi
fi

# Check Redis
if command -v redis-server &> /dev/null; then
    REDIS_VERSION=$(redis-server --version | head -n1)
    print_success "Redis found: $REDIS_VERSION"
else
    print_warning "Redis not found. Please install Redis for caching and sessions."
    if [[ "$PLATFORM" == "macOS" ]]; then
        print_status "Install with: brew install redis"
    elif [[ "$PLATFORM" == "Linux" ]]; then
        print_status "Install with: sudo apt-get install redis-server"
    fi
fi

echo ""

# =============================================================================
# 2. INSTALL DEPENDENCIES
# =============================================================================
print_status "Installing project dependencies..."

# Install root dependencies
print_status "Installing root dependencies..."
npm install

# Install client dependencies
print_status "Installing client dependencies..."
cd client
npm install --legacy-peer-deps
cd ..

# Install server dependencies
print_status "Installing server dependencies..."
cd server
npm install --legacy-peer-deps
cd ..

# Install AI services dependencies
if command -v python3 &> /dev/null; then
    print_status "Installing AI services dependencies..."
    cd agents
    if [ -f requirements.txt ]; then
        python3 -m pip install -r requirements.txt
    fi
    cd ..
fi

print_success "All dependencies installed successfully!"

echo ""

# =============================================================================
# 3. SETUP ENVIRONMENT VARIABLES
# =============================================================================
print_status "Setting up environment variables..."

# Copy development environment template
if [ -f "development.env" ]; then
    if [ ! -f ".env" ]; then
        cp development.env .env
        print_success "Environment variables configured from development.env"
    else
        print_warning ".env file already exists. Skipping environment setup."
    fi
else
    print_warning "development.env template not found. Please create .env manually."
fi

echo ""

# =============================================================================
# 4. SETUP DATABASE
# =============================================================================
print_status "Setting up development database..."

# Start MongoDB if not running
if command -v mongod &> /dev/null; then
    if ! pgrep -x "mongod" > /dev/null; then
        print_status "Starting MongoDB..."
        if [[ "$PLATFORM" == "macOS" ]]; then
            brew services start mongodb-community
        elif [[ "$PLATFORM" == "Linux" ]]; then
            sudo systemctl start mongod
        fi
        sleep 3
    else
        print_success "MongoDB is already running"
    fi
fi

# Start Redis if not running
if command -v redis-server &> /dev/null; then
    if ! pgrep -x "redis-server" > /dev/null; then
        print_status "Starting Redis..."
        if [[ "$PLATFORM" == "macOS" ]]; then
            brew services start redis
        elif [[ "$PLATFORM" == "Linux" ]]; then
            sudo systemctl start redis-server
        fi
        sleep 2
    else
        print_success "Redis is already running"
    fi
fi

echo ""

# =============================================================================
# 5. SEED DEVELOPMENT DATA
# =============================================================================
print_status "Seeding development database..."

cd server
if [ -f "package.json" ] && grep -q "seed" package.json; then
    npm run seed
    print_success "Development data seeded successfully!"
else
    print_warning "No seed script found. Skipping database seeding."
fi
cd ..

echo ""

# =============================================================================
# 6. CREATE DEVELOPMENT SCRIPTS
# =============================================================================
print_status "Creating development scripts..."

# Create start development script
cat > start-dev.sh << 'EOF'
#!/bin/bash
echo "🚀 Starting LUDUS Platform Development Environment..."

# Start MongoDB
if command -v mongod &> /dev/null && ! pgrep -x "mongod" > /dev/null; then
    echo "Starting MongoDB..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew services start mongodb-community
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        sudo systemctl start mongod
    fi
fi

# Start Redis
if command -v redis-server &> /dev/null && ! pgrep -x "redis-server" > /dev/null; then
    echo "Starting Redis..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew services start redis
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        sudo systemctl start redis-server
    fi
fi

# Start development servers
echo "Starting development servers..."
npm run dev
EOF

chmod +x start-dev.sh

# Create stop development script
cat > stop-dev.sh << 'EOF'
#!/bin/bash
echo "🛑 Stopping LUDUS Platform Development Environment..."

# Stop development servers
pkill -f "react-scripts start" || true
pkill -f "nodemon" || true

# Stop MongoDB
if command -v mongod &> /dev/null; then
    echo "Stopping MongoDB..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew services stop mongodb-community
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        sudo systemctl stop mongod
    fi
fi

# Stop Redis
if command -v redis-server &> /dev/null; then
    echo "Stopping Redis..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew services stop redis
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        sudo systemctl stop redis-server
    fi
fi

echo "✅ Development environment stopped"
EOF

chmod +x stop-dev.sh

print_success "Development scripts created!"

echo ""

# =============================================================================
# 7. VERIFY SETUP
# =============================================================================
print_status "Verifying development environment setup..."

# Test Node.js modules
print_status "Testing Node.js modules..."
cd server
if npm list express &> /dev/null; then
    print_success "Server dependencies verified"
else
    print_error "Server dependencies not properly installed"
fi
cd ..

cd client
if npm list react &> /dev/null; then
    print_success "Client dependencies verified"
else
    print_error "Client dependencies not properly installed"
fi
cd ..

# Test database connection
print_status "Testing database connection..."
cd server
if node -e "
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/ludus_dev', { useNewUrlParser: true, useUnifiedTopology: true })
  .then(() => { console.log('✅ Database connection successful'); process.exit(0); })
  .catch(err => { console.log('❌ Database connection failed:', err.message); process.exit(1); });
" 2>/dev/null; then
    print_success "Database connection verified"
else
    print_warning "Database connection test failed. Make sure MongoDB is running."
fi
cd ..

echo ""

# =============================================================================
# 8. COMPLETION SUMMARY
# =============================================================================
print_success "🎉 Development environment setup completed!"
echo ""
echo "📋 Next Steps:"
echo "1. Update .env file with your actual API keys and credentials"
echo "2. Run './start-dev.sh' to start the development environment"
echo "3. Open http://localhost:3000 for the frontend"
echo "4. Open http://localhost:5000 for the backend API"
echo ""
echo "🛠️  Available Commands:"
echo "  ./start-dev.sh     - Start development environment"
echo "  ./stop-dev.sh      - Stop development environment"
echo "  npm run dev        - Start both frontend and backend"
echo "  npm run build      - Build for production"
echo "  npm run test       - Run tests"
echo ""
echo "📚 Documentation:"
echo "  - Technical Architecture: LUDUS_TECHNICAL_ARCHITECTURE.md"
echo "  - API Specifications: LUDUS_API_SPECIFICATIONS.md"
echo "  - Database Schema: LUDUS_DATABASE_SCHEMA.md"
echo "  - Security Requirements: LUDUS_SECURITY_REQUIREMENTS.md"
echo ""
print_success "Happy coding! 🚀"
